version: "2"

services:
  recorder:
    build: .
    command: bundle exec ruby recorder.rb --users_yaml=/conf/users.yml --rec_dir_name=/output
    environment:
      ACCESS_TOKEN: $ACCESS_TOKEN
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - $OUTPUT_DIR:/output
